// Package scenario renders production-shaped /etc/sysconfig/heat-params files
// for e2e tests. The field set mirrors magnum_victoria's
// write-heat-params-master.sh / write-heat-params.sh so the reconciler sees
// exactly what a real Magnum-provisioned node would.
//
// The whole point is that an operation is just a different heat-params file:
//
//	create    -> baseline heat-params, no CA_ROTATION_ID
//	upgrade   -> bumped KUBE_TAG (detected by the reconciler as a version delta)
//	resize    -> changed node count (no node-local flag; convergence is state-driven)
//	ca-rotate -> CA_ROTATION_ID set to a new value
//
// There are no IS_UPGRADE / IS_RESIZE flags: the reconciler infers all intent
// from desired state (KUBE_TAG, node count, rotation token) vs applied state.
//
// Role (master/worker) and operation are detected by internal/config from this
// file alone, so the same Config drives the mock-VM tier and the real-OpenStack
// tier — only CloudProvider and the binary-delivery fields change.
package scenario

import (
	"fmt"
	"strings"
)

type Role string

const (
	RoleMaster Role = "master"
	RoleWorker Role = "worker"
)

type Operation string

const (
	OpCreate   Operation = "create"
	OpUpgrade  Operation = "upgrade"
	OpResize   Operation = "resize"
	OpCARotate Operation = "ca-rotate"
)

// Config is the minimal-but-faithful input for one node in one scenario.
// Secret-ish material (CAKey, SA keypair) is supplied by the harness, which
// generates it alongside the mock Magnum CA so cert and key share one CA.
type Config struct {
	ClusterName string
	Role        Role
	NodeIndex   int
	Operation   Operation

	// Networking / identity.
	NodeIP string // KUBE_NODE_IP (set explicitly so the metadata service is never needed)
	APIIP  string // master: API server address -> KUBE_API_PRIVATE/PUBLIC_ADDRESS. In a
	// multi-master cluster this is the api_lb VIP (same on every master); single-master
	// defaults to NodeIP.
	EtcdLBVIP string // master: etcd_lb VIP -> ETCD_LB_VIP. Set to the etcd_lb VIP whenever
	// the LB is enabled; joining masters reach existing members through it. A first/single
	// master bootstraps from the static initial-cluster regardless (the LB has no backend yet).
	InitialCluster string // master: ETCD_INITIAL_CLUSTER -> static etcd member list
	// ("name0=https://ip0:2380,..."). Empty for a first/single master (the etcd module
	// then bootstraps a one-node cluster from its own peer URL); set to the full member
	// list to bootstrap a multi-master cluster all at once without v2 discovery.
	MasterIP string // worker: KUBE_MASTER_IP (the API server address to join — the api_lb VIP in multi-master)
	KubeTag  string // e.g. v1.30.5 (kubelet/kubectl URLs are derived from this)

	// CA-rotate trigger. Leave empty except for OpCARotate.
	CARotationID string

	// Mock or real Magnum/Keystone endpoints.
	AuthURL     string
	MagnumURL   string
	ClusterUUID string

	// Shared CA + service-account keypair (PEM). Generated by the harness.
	CAKey        string // -> /etc/kubernetes/certs/ca.key (must match the CA the mock serves)
	SAKey        string // KUBE_SERVICE_ACCOUNT_KEY (public)
	SAPrivateKey string // KUBE_SERVICE_ACCOUNT_PRIVATE_KEY

	// CloudProvider flips every OpenStack-integrated piece together: external
	// cloud provider, OCCM, Cinder CSI, Manila CSI, Octavia. Keep false on the
	// mock-VM tier (no real Nova/Neutron/Cinder), true on real OpenStack.
	CloudProvider bool

	// Container runtime selection.
	ContainerRuntime string // default "containerd"
	UsePodman        bool   // master control-plane components run via podman

	// Reconciler binary delivery (the launcher downloads this). For PR builds
	// the harness serves the freshly built binary over file:// or a local HTTP
	// server instead of a GitHub release.
	ReconcilerVersion         string
	ReconcilerBinaryURL       string
	ReconcilerBinaryURLSHA256 string

	// NumberOfMasters is written as NUMBER_OF_MASTERS (default 1). Multi-master
	// scenarios set this so the reconciler serializes control-plane restarts.
	NumberOfMasters int

	// Per-nodegroup node metadata, written as NODE_LABELS / NODE_TAINTS
	// ("k1=v1;k2=v2" / "key=value:Effect;..."). Empty = none (the production
	// default for clusters without the feature).
	NodeLabels string
	NodeTaints string

	// RunTimeoutSeconds -> RECONCILER_RUN_TIMEOUT_SECONDS (default 4800). The
	// launcher sources heat-params, so this is the Heat-driven reconcile budget
	// the binary self-cancels within; e2e must carry it to exercise that path.
	RunTimeoutSeconds int

	// Optional overrides (sensible defaults applied when empty).
	Arch               string // default amd64
	FlannelNetworkCIDR string // default 10.100.0.0/16
	PodsNetworkCIDR    string // default 10.100.0.0/16
	PortalNetworkCIDR  string // default 10.254.0.0/16
	DNSServiceIP       string // default 10.254.0.10
	DNSClusterDomain   string // default cluster.local
	KubeAPIPort        int    // default 6443
}

// InstanceName is the node's Magnum instance name. Masters must end in
// "master-0" for the first master so cluster addons run there
// (config.IsFirstMaster).
func (c Config) InstanceName() string {
	word := "master"
	if c.Role == RoleWorker {
		word = "minion"
	}
	return fmt.Sprintf("%s-%s-%d", c.ClusterName, word, c.NodeIndex)
}

func (c Config) withDefaults() Config {
	d := c
	if d.Arch == "" {
		d.Arch = "amd64"
	}
	if d.ContainerRuntime == "" {
		d.ContainerRuntime = "containerd"
	}
	if d.FlannelNetworkCIDR == "" {
		d.FlannelNetworkCIDR = "10.100.0.0/16"
	}
	if d.PodsNetworkCIDR == "" {
		d.PodsNetworkCIDR = "10.100.0.0/16"
	}
	if d.PortalNetworkCIDR == "" {
		d.PortalNetworkCIDR = "10.254.0.0/16"
	}
	if d.DNSServiceIP == "" {
		d.DNSServiceIP = "10.254.0.10"
	}
	if d.DNSClusterDomain == "" {
		d.DNSClusterDomain = "cluster.local"
	}
	if d.KubeAPIPort == 0 {
		d.KubeAPIPort = 6443
	}
	if d.NumberOfMasters == 0 {
		d.NumberOfMasters = 1
	}
	if d.RunTimeoutSeconds == 0 {
		d.RunTimeoutSeconds = 4800
	}
	if d.APIIP == "" {
		d.APIIP = d.NodeIP
	}
	return d
}

func b(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

// KV is one ordered key/value pair, shared by the rendered heat-params file and
// the Heat SoftwareDeployment input_values.
type KV struct {
	Name  string
	Value string
}

// HeatParams renders the heat-params file content for this scenario.
func (c Config) HeatParams() string {
	var sb strings.Builder
	for _, kv := range c.pairs() {
		fmt.Fprintf(&sb, "%s=%q\n", kv.Name, kv.Value)
	}
	return sb.String()
}

// Inputs returns the ordered Heat SoftwareDeployment input_values for this
// scenario — the same keys/values write-heat-params*.sh consumes from the
// environment. The heat-container-agent path feeds these as env vars so the
// agent renders an equivalent /etc/sysconfig/heat-params, exactly like Heat.
func (c Config) Inputs() []KV { return c.pairs() }

// pairs builds the ordered key/value set behind both HeatParams and Inputs.
func (c Config) pairs() []KV {
	c = c.withDefaults()

	caRotationID := c.CARotationID
	if c.Operation != OpCARotate {
		caRotationID = ""
	}

	volumeDriver := ""
	if c.CloudProvider {
		volumeDriver = "cinder"
	}

	var kvs []KV
	put := func(k, v string) { kvs = append(kvs, KV{Name: k, Value: v}) }

	// Common fields (present for both roles).
	put("ARCH", c.Arch)
	put("INSTANCE_NAME", c.InstanceName())
	put("NODEGROUP_ROLE", string(c.Role))
	put("NODEGROUP_NAME", string(c.Role)+"-group")
	put("KUBE_TAG", c.KubeTag)
	put("KUBE_VERSION", c.KubeTag)
	put("KUBE_NODE_IP", c.NodeIP)
	put("KUBE_NODE_PUBLIC_IP", c.NodeIP)
	put("KUBE_API_PORT", fmt.Sprint(c.KubeAPIPort))
	put("KUBE_ALLOW_PRIV", "true")
	put("TLS_DISABLED", "false")
	put("VERIFY_CA", "false")
	put("CLUSTER_UUID", c.ClusterUUID)
	put("MAGNUM_URL", c.MagnumURL)
	put("AUTH_URL", c.AuthURL)
	put("TRUSTEE_USER_ID", "mock-trustee")
	put("TRUSTEE_USERNAME", "mock-trustee")
	put("TRUSTEE_PASSWORD", "mock-password")
	put("TRUSTEE_DOMAIN_ID", "default")
	put("TRUST_ID", "mock-trust")
	put("CA_KEY", c.CAKey)
	put("KUBE_SERVICE_ACCOUNT_KEY", c.SAKey)
	put("KUBE_SERVICE_ACCOUNT_PRIVATE_KEY", c.SAPrivateKey)
	put("CA_ROTATION_ID", caRotationID)
	put("NETWORK_DRIVER", "flannel")
	put("FLANNEL_NETWORK_CIDR", c.FlannelNetworkCIDR)
	put("FLANNEL_BACKEND", "vxlan")
	put("PODS_NETWORK_CIDR", c.PodsNetworkCIDR)
	put("PORTAL_NETWORK_CIDR", c.PortalNetworkCIDR)
	put("DNS_SERVICE_IP", c.DNSServiceIP)
	put("DNS_CLUSTER_DOMAIN", c.DNSClusterDomain)
	put("CONTAINER_RUNTIME", c.ContainerRuntime)
	put("USE_PODMAN", b(c.UsePodman))
	put("CONTAINER_INFRA_PREFIX", "")
	// heat-container-agent image tag the reconciler converges (empty = leave the
	// node's baked agent tag untouched). See heat-container-agent module.
	put("HEAT_CONTAINER_AGENT_TAG", "")
	put("REGION_NAME", "RegionOne")
	put("HTTP_PROXY", "")
	put("HTTPS_PROXY", "")
	put("NO_PROXY", "")
	put("OS_AUTOUPGRADE_ENABLED", "false")

	// Storage: no extra block device on the mock VM tier -> empty volumes so
	// the storage module uses ephemeral paths instead of waiting for /dev/vdb.
	put("ENABLE_CINDER", b(c.CloudProvider))
	put("DOCKER_VOLUME", "")
	put("DOCKER_VOLUME_SIZE", "0")
	put("DOCKER_STORAGE_DRIVER", "overlay2")
	put("VOLUME_DRIVER", volumeDriver)

	// Cloud-provider-integrated features (real OpenStack only).
	put("CLOUD_PROVIDER_ENABLED", b(c.CloudProvider))
	put("OCTAVIA_ENABLED", b(c.CloudProvider))
	put("CINDER_CSI_ENABLED", b(c.CloudProvider))
	put("MANILA_CSI_ENABLED", b(c.CloudProvider))
	put("KEYSTONE_AUTH_ENABLED", "false")

	// Cluster-addon toggles kept conservative for self-contained runs.
	put("METRICS_SERVER_ENABLED", "true")
	put("KUBE_DASHBOARD_ENABLED", "false")
	put("AUTO_HEALING_ENABLED", "false")
	put("AUTO_HEALING_CONTROLLER", "")
	put("AUTO_SCALING_ENABLED", "false")
	put("GPU_OPERATOR_ENABLED", "false")
	put("CERT_MANAGER_API", "true")

	// Per-nodegroup node metadata (empty -> none; see NodeLabels/NodeTaints).
	put("NODE_LABELS", c.NodeLabels)
	put("NODE_TAINTS", c.NodeTaints)

	// Component option passthroughs (empty -> reconciler defaults).
	put("KUBELET_OPTIONS", "")
	put("KUBEAPI_OPTIONS", "")
	put("KUBECONTROLLER_OPTIONS", "")
	put("KUBEPROXY_OPTIONS", "")
	put("ADMISSION_CONTROL_LIST", "")
	put("INSECURE_REGISTRY_URL", "")
	put("POST_INSTALL_MANIFEST_URL", "")

	switch c.Role {
	case RoleMaster:
		put("NUMBER_OF_MASTERS", fmt.Sprint(c.NumberOfMasters))
		// MASTER_INDEX: the binary reads it (config.heatparams), but note the real
		// driver does NOT currently write it (a magnum_victoria gap tracked in the
		// contract guard's scenarioExtras). We emit the correct value here.
		put("MASTER_INDEX", fmt.Sprint(c.NodeIndex))
		put("KUBE_API_PRIVATE_ADDRESS", c.APIIP)
		put("KUBE_API_PUBLIC_ADDRESS", c.APIIP)
		put("ETCD_LB_VIP", c.EtcdLBVIP)
		put("ETCD_INITIAL_CLUSTER", c.InitialCluster)
		put("ETCD_VOLUME", "")
		put("ETCD_VOLUME_SIZE", "0")
		put("LEAD_NODE_ROLE_NAME", leadNodeRole(c.KubeTag))
		// Master-only fields the real write-heat-params-master.sh emits. Cloud /
		// autoscaler / image fields are empty on the self-contained tier (no real
		// OpenStack); SELINUX_MODE/TIMESTAMP_UPGRADE are node metadata. The test
		// node boots SELinux permissive (butane) to match production Magnum nodes,
		// whose cluster selinux_mode default is non-enforcing.
		put("SELINUX_MODE", "permissive")
		put("TIMESTAMP_UPGRADE", "")
		put("CLUSTER_NETWORK_NAME", "")
		put("CLUSTER_SUBNET", "")
		put("EXTERNAL_NETWORK_ID", "")
		put("KUBE_IMAGE_DIGEST", "")
		put("MIN_NODE_COUNT", "")
		put("MAX_NODE_COUNT", "")
	case RoleWorker:
		put("KUBE_MASTER_IP", c.MasterIP)
		put("ETCD_SERVER_IP", c.MasterIP)
		put("REGISTRY_ENABLED", "false")
		put("REGISTRY_PORT", "5000")
		put("REGISTRY_INSECURE", "true")
		// Worker-only registry/swift fields the real write-heat-params.sh emits
		// (empty/unused while the in-cluster registry is disabled).
		put("SWIFT_REGION", "")
		put("REGISTRY_CONTAINER", "")
		put("REGISTRY_CHUNKSIZE", "")
	}

	// Reconciler binary delivery (consumed by the launcher, not the binary).
	put("RECONCILER_VERSION", c.ReconcilerVersion)
	put("RECONCILER_BINARY_URL", c.ReconcilerBinaryURL)
	put("RECONCILER_BINARY_URL_SHA256", c.ReconcilerBinaryURLSHA256)
	put("RECONCILER_LOCK_TIMEOUT_SECONDS", "900")
	put("RECONCILER_RUN_TIMEOUT_SECONDS", fmt.Sprint(c.RunTimeoutSeconds))

	return kvs
}

// leadNodeRole mirrors write-heat-params-master.sh: the control-plane node role
// label name changed from "master" to "control-plane" in Kubernetes 1.25.
func leadNodeRole(kubeTag string) string {
	if kubeMinorAtLeast(kubeTag, 25) {
		return "control-plane"
	}
	return "master"
}

func kubeMinorAtLeast(kubeTag string, minor int) bool {
	v := strings.TrimPrefix(strings.TrimSpace(kubeTag), "v")
	parts := strings.SplitN(v, ".", 3)
	if len(parts) < 2 {
		return false
	}
	var got int
	if _, err := fmt.Sscanf(parts[1], "%d", &got); err != nil {
		return false
	}
	return got >= minor
}
