// Package scenario renders production-shaped /etc/sysconfig/heat-params files
// for e2e tests. The field set mirrors magnum_victoria's
// write-heat-params-master.sh / write-heat-params.sh so the reconciler sees
// exactly what a real Magnum-provisioned node would.
//
// The whole point is that an operation is just a different heat-params file:
//
//	create    -> IS_UPGRADE=false IS_RESIZE=false, no CA_ROTATION_ID
//	upgrade   -> IS_UPGRADE=true  (+ bumped KUBE_TAG)
//	resize    -> IS_RESIZE=true
//	ca-rotate -> CA_ROTATION_ID set to a new value
//
// Role (master/worker) and operation are detected by internal/config from this
// file alone, so the same Config drives the mock-VM tier and the real-OpenStack
// tier — only CloudProvider and the binary-delivery fields change.
package scenario

import (
	"fmt"
	"strings"
)

type Role string

const (
	RoleMaster Role = "master"
	RoleWorker Role = "worker"
)

type Operation string

const (
	OpCreate   Operation = "create"
	OpUpgrade  Operation = "upgrade"
	OpResize   Operation = "resize"
	OpCARotate Operation = "ca-rotate"
)

// Config is the minimal-but-faithful input for one node in one scenario.
// Secret-ish material (CAKey, SA keypair) is supplied by the harness, which
// generates it alongside the mock Magnum CA so cert and key share one CA.
type Config struct {
	ClusterName string
	Role        Role
	NodeIndex   int
	Operation   Operation

	// Networking / identity.
	NodeIP   string // KUBE_NODE_IP (set explicitly so the metadata service is never needed)
	APIIP    string // master: API address; also used as ETCD/LB address for single-master
	MasterIP string // worker: KUBE_MASTER_IP (the API server address to join)
	KubeTag  string // e.g. v1.30.5 (kubelet/kubectl URLs are derived from this)

	// CA-rotate trigger. Leave empty except for OpCARotate.
	CARotationID string

	// Mock or real Magnum/Keystone endpoints.
	AuthURL     string
	MagnumURL   string
	ClusterUUID string

	// Shared CA + service-account keypair (PEM). Generated by the harness.
	CAKey        string // -> /etc/kubernetes/certs/ca.key (must match the CA the mock serves)
	SAKey        string // KUBE_SERVICE_ACCOUNT_KEY (public)
	SAPrivateKey string // KUBE_SERVICE_ACCOUNT_PRIVATE_KEY

	// CloudProvider flips every OpenStack-integrated piece together: external
	// cloud provider, OCCM, Cinder CSI, Manila CSI, Octavia. Keep false on the
	// mock-VM tier (no real Nova/Neutron/Cinder), true on real OpenStack.
	CloudProvider bool

	// Container runtime selection.
	ContainerRuntime string // default "containerd"
	UsePodman        bool   // master control-plane components run via podman

	// Reconciler binary delivery (the launcher downloads this). For PR builds
	// the harness serves the freshly built binary over file:// or a local HTTP
	// server instead of a GitHub release.
	ReconcilerVersion         string
	ReconcilerBinaryURL       string
	ReconcilerBinaryURLSHA256 string

	// Optional overrides (sensible defaults applied when empty).
	Arch               string // default amd64
	FlannelNetworkCIDR string // default 10.100.0.0/16
	PodsNetworkCIDR    string // default 10.100.0.0/16
	PortalNetworkCIDR  string // default 10.254.0.0/16
	DNSServiceIP       string // default 10.254.0.10
	DNSClusterDomain   string // default cluster.local
	KubeAPIPort        int    // default 6443
}

// InstanceName is the node's Magnum instance name. Masters must end in
// "master-0" for the first master so cluster addons run there
// (config.IsFirstMaster).
func (c Config) InstanceName() string {
	word := "master"
	if c.Role == RoleWorker {
		word = "minion"
	}
	return fmt.Sprintf("%s-%s-%d", c.ClusterName, word, c.NodeIndex)
}

func (c Config) withDefaults() Config {
	d := c
	if d.Arch == "" {
		d.Arch = "amd64"
	}
	if d.ContainerRuntime == "" {
		d.ContainerRuntime = "containerd"
	}
	if d.FlannelNetworkCIDR == "" {
		d.FlannelNetworkCIDR = "10.100.0.0/16"
	}
	if d.PodsNetworkCIDR == "" {
		d.PodsNetworkCIDR = "10.100.0.0/16"
	}
	if d.PortalNetworkCIDR == "" {
		d.PortalNetworkCIDR = "10.254.0.0/16"
	}
	if d.DNSServiceIP == "" {
		d.DNSServiceIP = "10.254.0.10"
	}
	if d.DNSClusterDomain == "" {
		d.DNSClusterDomain = "cluster.local"
	}
	if d.KubeAPIPort == 0 {
		d.KubeAPIPort = 6443
	}
	if d.APIIP == "" {
		d.APIIP = d.NodeIP
	}
	return d
}

func b(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

// HeatParams renders the heat-params file content for this scenario.
func (c Config) HeatParams() string {
	c = c.withDefaults()

	isUpgrade := c.Operation == OpUpgrade
	isResize := c.Operation == OpResize
	caRotationID := c.CARotationID
	if c.Operation != OpCARotate {
		caRotationID = ""
	}

	volumeDriver := ""
	if c.CloudProvider {
		volumeDriver = "cinder"
	}

	var sb strings.Builder
	put := func(k, v string) { fmt.Fprintf(&sb, "%s=%q\n", k, v) }

	// Common fields (present for both roles).
	put("ARCH", c.Arch)
	put("INSTANCE_NAME", c.InstanceName())
	put("NODEGROUP_ROLE", string(c.Role))
	put("NODEGROUP_NAME", string(c.Role)+"-group")
	put("IS_UPGRADE", b(isUpgrade))
	put("IS_RESIZE", b(isResize))
	put("KUBE_TAG", c.KubeTag)
	put("KUBE_VERSION", c.KubeTag)
	put("KUBE_NODE_IP", c.NodeIP)
	put("KUBE_NODE_PUBLIC_IP", c.NodeIP)
	put("KUBE_API_PORT", fmt.Sprint(c.KubeAPIPort))
	put("KUBE_ALLOW_PRIV", "true")
	put("TLS_DISABLED", "false")
	put("VERIFY_CA", "false")
	put("CLUSTER_UUID", c.ClusterUUID)
	put("MAGNUM_URL", c.MagnumURL)
	put("AUTH_URL", c.AuthURL)
	put("TRUSTEE_USER_ID", "mock-trustee")
	put("TRUSTEE_USERNAME", "mock-trustee")
	put("TRUSTEE_PASSWORD", "mock-password")
	put("TRUSTEE_DOMAIN_ID", "default")
	put("TRUST_ID", "mock-trust")
	put("CA_KEY", c.CAKey)
	put("KUBE_SERVICE_ACCOUNT_KEY", c.SAKey)
	put("KUBE_SERVICE_ACCOUNT_PRIVATE_KEY", c.SAPrivateKey)
	put("CA_ROTATION_ID", caRotationID)
	put("NETWORK_DRIVER", "flannel")
	put("FLANNEL_NETWORK_CIDR", c.FlannelNetworkCIDR)
	put("FLANNEL_BACKEND", "vxlan")
	put("PODS_NETWORK_CIDR", c.PodsNetworkCIDR)
	put("PORTAL_NETWORK_CIDR", c.PortalNetworkCIDR)
	put("DNS_SERVICE_IP", c.DNSServiceIP)
	put("DNS_CLUSTER_DOMAIN", c.DNSClusterDomain)
	put("CONTAINER_RUNTIME", c.ContainerRuntime)
	put("USE_PODMAN", b(c.UsePodman))
	put("CONTAINER_INFRA_PREFIX", "")
	put("REGION_NAME", "RegionOne")
	put("HTTP_PROXY", "")
	put("HTTPS_PROXY", "")
	put("NO_PROXY", "")
	put("OS_AUTOUPGRADE_ENABLED", "false")

	// Storage: no extra block device on the mock VM tier -> empty volumes so
	// the storage module uses ephemeral paths instead of waiting for /dev/vdb.
	put("ENABLE_CINDER", b(c.CloudProvider))
	put("DOCKER_VOLUME", "")
	put("DOCKER_VOLUME_SIZE", "0")
	put("DOCKER_STORAGE_DRIVER", "overlay2")
	put("VOLUME_DRIVER", volumeDriver)

	// Cloud-provider-integrated features (real OpenStack only).
	put("CLOUD_PROVIDER_ENABLED", b(c.CloudProvider))
	put("OCTAVIA_ENABLED", b(c.CloudProvider))
	put("CINDER_CSI_ENABLED", b(c.CloudProvider))
	put("MANILA_CSI_ENABLED", b(c.CloudProvider))
	put("KEYSTONE_AUTH_ENABLED", "false")

	// Cluster-addon toggles kept conservative for self-contained runs.
	put("METRICS_SERVER_ENABLED", "true")
	put("KUBE_DASHBOARD_ENABLED", "false")
	put("AUTO_HEALING_ENABLED", "false")
	put("AUTO_HEALING_CONTROLLER", "")
	put("AUTO_SCALING_ENABLED", "false")
	put("GPU_OPERATOR_ENABLED", "false")
	put("CERT_MANAGER_API", "true")

	// Component option passthroughs (empty -> reconciler defaults).
	put("KUBELET_OPTIONS", "")
	put("KUBEAPI_OPTIONS", "")
	put("KUBECONTROLLER_OPTIONS", "")
	put("KUBEPROXY_OPTIONS", "")
	put("ADMISSION_CONTROL_LIST", "")
	put("INSECURE_REGISTRY_URL", "")
	put("POST_INSTALL_MANIFEST_URL", "")

	switch c.Role {
	case RoleMaster:
		put("NUMBER_OF_MASTERS", "1")
		put("MASTER_INDEX", fmt.Sprint(c.NodeIndex))
		put("KUBE_API_PRIVATE_ADDRESS", c.APIIP)
		put("KUBE_API_PUBLIC_ADDRESS", c.APIIP)
		put("ETCD_LB_VIP", "")
		put("ETCD_DISCOVERY_URL", "")
		put("ETCD_VOLUME", "")
		put("ETCD_VOLUME_SIZE", "0")
		put("LEAD_NODE_ROLE_NAME", leadNodeRole(c.KubeTag))
	case RoleWorker:
		put("KUBE_MASTER_IP", c.MasterIP)
		put("ETCD_SERVER_IP", c.MasterIP)
		put("REGISTRY_ENABLED", "false")
		put("REGISTRY_PORT", "5000")
		put("REGISTRY_INSECURE", "true")
	}

	// Reconciler binary delivery (consumed by the launcher, not the binary).
	put("RECONCILER_VERSION", c.ReconcilerVersion)
	put("RECONCILER_BINARY_URL", c.ReconcilerBinaryURL)
	put("RECONCILER_BINARY_URL_SHA256", c.ReconcilerBinaryURLSHA256)
	put("RECONCILER_LOCK_TIMEOUT_SECONDS", "900")

	return sb.String()
}

// leadNodeRole mirrors write-heat-params-master.sh: the control-plane node role
// label name changed from "master" to "control-plane" in Kubernetes 1.25.
func leadNodeRole(kubeTag string) string {
	if kubeMinorAtLeast(kubeTag, 25) {
		return "control-plane"
	}
	return "master"
}

func kubeMinorAtLeast(kubeTag string, minor int) bool {
	v := strings.TrimPrefix(strings.TrimSpace(kubeTag), "v")
	parts := strings.SplitN(v, ".", 3)
	if len(parts) < 2 {
		return false
	}
	var got int
	if _, err := fmt.Sscanf(parts[1], "%d", &got); err != nil {
		return false
	}
	return got >= minor
}
